name: Verify changes

on: pull_request

jobs:
  setup-common-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: google/wireit@setup-github-actions-caching/v1

  verify:
    name: Verify changes
    runs-on: ubuntu-latest
    needs: setup-common-steps
    steps:
      - name: Sanity check
        run: node ./scripts/lock-scan.js

      - name: Setup Node 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm install --ci

      - name: Lint
        run: npm run lint

      - name: Bundlesize
        run: npm run bundlesize

  browser-tests:
    name: Browser tests
    runs-on: ubuntu-latest
    needs: setup-common-steps
    steps:
      - name: Setup Node 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm install --ci

      - uses: microsoft/playwright-github-action@v1

      - name: Test
        run: npm run test:browser

  node-tests:
    name: Node tests
    needs: setup-common-steps
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
    steps:
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install --ci

      - name: Test
        run: npm run test:node

  # Note this is a duplicate of the matrix (so we have 2 1x1 matrices). Up for improvement...
  node-tests-windows:
    name: Node tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x]
        os: [windows-latest]
    steps:
      - needs: setup-common-steps

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install --ci

      - name: Test
        run: npm run test:node
